### ISSUE TITLE
Is it OK to run docker from inside a Vagrant box?

### ISSUE THREAD

**Issue by mpdude** [matthiasnoback/docker-swarm-workshop#5]
Hi Matthias,

working with an OS X notebook, I usually use Vagrant and Virtualbox to run Ubuntu VMs for my various projects. 

So, regarding your installation instructions, would it be OK to have Docker installed in a recent Ubuntu VM?

As you're also listing Virtualbox as a requirement, I wonder if Docker might need to be installed on the Host OS to run a swarm of VMs... hey wait, what is a *swarm* :-)?

Thanks!

**Comment by matthiasnoback** [comment]
Hi!
Yeah, it's fine to run Docker in a VM. When working with Swarm there is a
handy online alternative, called play-with-docker, which you can use for
free during the workshop.
